

spring:
  datasource: #数据源配置
    url: jdbc:mysql://localhost:3306/beerate_web?useUnicode=true&characterEncoding=utf8&serverTimezone=CTT
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa: #jpa配置
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    open-in-view: true
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
  mvc: #表示所有的访问都经过静态资源路径
    static-path-pattern: /**
#  resources:
#    static-locations:

  #thymelea模板配置
  thymeleaf:
    prefix: "classpath:/templates/"
    suffix: ".html"
    mode: "HTML5"
    encoding: "UTF-8"
    cache: false
  servlet:
    multipart:
      enabled: true
      max-request-size: 209715200 #限制上传的多个文件的总大小
      max-file-size: 104857600 #限制单个文件的最大值
      location: #上传文件的临时目录



#系统参数
cn:
  beerate:
    file:
      admin-file: /admin
      temp-file:  /temp
      user-file:  /user
    security:
      password-md5-salt: wGyUtsswIYAMxHdW

